#!/bin/bash

echo "================================================================================"
echo " Kenny's OS - Database Migration SQL"
echo "================================================================================"
echo ""
echo "Copy EVERYTHING below (between the markers) and paste into Supabase SQL Editor:"
echo "https://supabase.com/dashboard/project/jtngcypnstmsdyurjtkn/editor"
echo ""
echo "▼▼▼ START COPYING HERE ▼▼▼"
echo "--------------------------------------------------------------------------------"
cat "$(dirname "$0")/../supabase/migrations/20260313_init_schema.sql"
echo "--------------------------------------------------------------------------------"
echo "▲▲▲ STOP COPYING HERE ▲▲▲"
echo ""
echo "After running in Supabase, test with:"
echo ""
echo "  npm run test:db"
echo ""
echo "Or manually:"
echo ""
echo "  curl -H \"apikey: \$VITE_SUPABASE_ANON_KEY\" \\"
echo "    -H \"Authorization: Bearer \$VITE_SUPABASE_ANON_KEY\" \\"
echo "    \"https://jtngcypnstmsdyurjtkn.supabase.co/rest/v1/kos_boards?select=*\""
echo ""
echo "================================================================================"
